// <auto-generated />
using System;
using EnsekTest.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnsekTest.Api.Migrations
{
    [DbContext(typeof(EnsekTestContext))]
    [Migration("20200830083508_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("EnsekTest.Shared.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 2344,
                            FirstName = "Tommy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2233,
                            FirstName = "Barry",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 8766,
                            FirstName = "Sally",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2345,
                            FirstName = "Jerry",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2346,
                            FirstName = "Ollie",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2347,
                            FirstName = "Tara",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2348,
                            FirstName = "Tammy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2349,
                            FirstName = "Simon",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2350,
                            FirstName = "Colin",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2351,
                            FirstName = "Gladys",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2352,
                            FirstName = "Greg",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2353,
                            FirstName = "Tony",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2355,
                            FirstName = "Arthur",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 2356,
                            FirstName = "Craig",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 6776,
                            FirstName = "Laura",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 4534,
                            FirstName = "JOSH",
                            LastName = "TEST"
                        },
                        new
                        {
                            Id = 1234,
                            FirstName = "Freya",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1239,
                            FirstName = "Noddy",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1240,
                            FirstName = "Archie",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1241,
                            FirstName = "Lara",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1242,
                            FirstName = "Tim",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1243,
                            FirstName = "Graham",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1244,
                            FirstName = "Tony",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1245,
                            FirstName = "Neville",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1246,
                            FirstName = "Jo",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1247,
                            FirstName = "Jim",
                            LastName = "Test"
                        },
                        new
                        {
                            Id = 1248,
                            FirstName = "Pam",
                            LastName = "Test"
                        });
                });

            modelBuilder.Entity("EnsekTest.Shared.Entities.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeterReadValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(5);

                    b.Property<DateTime>("MeterReadingDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("MeterReadings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 2344,
                            MeterReadValue = "01002",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2233,
                            MeterReadValue = "00323",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 8766,
                            MeterReadValue = "03440",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 2344,
                            MeterReadValue = "01002",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 2345,
                            MeterReadValue = "45522",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 2346,
                            MeterReadValue = "999999",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 2347,
                            MeterReadValue = "00054",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 2348,
                            MeterReadValue = "00123",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 2350,
                            MeterReadValue = "05684",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 2351,
                            MeterReadValue = "57579",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 2352,
                            MeterReadValue = "00455",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 2353,
                            MeterReadValue = "01212",
                            MeterReadingDateTime = new DateTime(2019, 4, 22, 12, 25, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 2355,
                            MeterReadValue = "00001",
                            MeterReadingDateTime = new DateTime(2019, 5, 6, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 2356,
                            MeterReadValue = "00000",
                            MeterReadingDateTime = new DateTime(2019, 5, 7, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 6776,
                            MeterReadValue = "-6575",
                            MeterReadingDateTime = new DateTime(2019, 5, 9, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 6776,
                            MeterReadValue = "23566",
                            MeterReadingDateTime = new DateTime(2019, 5, 10, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 1234,
                            MeterReadValue = "09787",
                            MeterReadingDateTime = new DateTime(2019, 5, 12, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 1239,
                            MeterReadValue = "45345",
                            MeterReadingDateTime = new DateTime(2019, 5, 17, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 1240,
                            MeterReadValue = "00978",
                            MeterReadingDateTime = new DateTime(2019, 5, 18, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 1241,
                            MeterReadValue = "00436",
                            MeterReadingDateTime = new DateTime(2019, 4, 11, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 1242,
                            MeterReadValue = "00124",
                            MeterReadingDateTime = new DateTime(2019, 5, 20, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 1243,
                            MeterReadValue = "00077",
                            MeterReadingDateTime = new DateTime(2019, 5, 21, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 1244,
                            MeterReadValue = "03478",
                            MeterReadingDateTime = new DateTime(2019, 5, 25, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 1245,
                            MeterReadValue = "00676",
                            MeterReadingDateTime = new DateTime(2019, 5, 25, 14, 26, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 1246,
                            MeterReadValue = "03455",
                            MeterReadingDateTime = new DateTime(2019, 5, 25, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 1247,
                            MeterReadValue = "00003",
                            MeterReadingDateTime = new DateTime(2019, 5, 25, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 1248,
                            MeterReadValue = "03467",
                            MeterReadingDateTime = new DateTime(2019, 5, 26, 9, 24, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EnsekTest.Shared.Entities.MeterReading", b =>
                {
                    b.HasOne("EnsekTest.Shared.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
